[package]
name = "aggregation-script"
version = "1.1.1"
edition = "2021"
publish = false

[dependencies]
hex = "0.4.3"
sp1-sdk = "1.1.1"
tracing = "0.1.40"

[build-dependencies]
sp1-build = "1.1.1"
sp1-helper = "1.1.1"
